module.exports = {
  parser: "@typescript-eslint/parser",
  parserOptions: {
    sourceType: "module",
    allowImportExportEverywhere: false,
    codeFrame: false,
    project: "tsconfig.json",
  },
  extends: [
    "airbnb",
    "airbnb-typescript",
    "plugin:@typescript-eslint/recommended",
    "prettier",
  ],
  plugins: ["prettier", "@typescript-eslint"],
  env: {
    browser: true,
    jest: true,
  },
  ignorePatterns: ["src/icons/*"],
  rules: {
    "comma-dangle": ["error", "always-multiline"],
    semi: 0,
    "import/no-cycle": 0,
    "import/no-unresolved": 0,
    "nonblock-statement-body-position": 0,
    "consistent-return": 0,
    "react/function-component-definition": [
      2,
      { namedComponents: "arrow-function" },
    ],
    "jsx-a11y/media-has-caption": 0,
    "react/jsx-props-no-spreading": 0,
    "react/no-unstable-nested-components": 0,
    "max-classes-per-file": 0,
    "import/prefer-default-export": 0,
    "@typescript-eslint/semi": 0,
    "class-methods-use-this": 0,
    "react/jsx-uses-react": 1,
    "no-console": ["warn", { allow: ["debug"] }],
    "max-len": ["warn", { code: 108 }],
    "react/prop-types": 0,
    "react/no-deprecated": "warn",
    "react/no-find-dom-node": "warn",
    "prettier/prettier": [
      "error",
      {
        semi: false,
        endOfLine: "auto",
      },
    ],
  },
};
